name: Premier workflow
on: workflow_dispatch
jobs:
    premier-job:
        name: mon premier job
        runs-on: ubuntu-latest
        steps:
            - name: Dit bonjour
              run: echo "Hello"
            - name: Dit au revoir
              run: echo "Good bye"
    second-job:
        name: mon second job
        runs-on: ubuntu-latest
        steps:
            - run: echo "jsuis le second job"